### ISSUE TITLE
Footer release date wrong

### ISSUE THREAD

**Issue by webmatros** [vaughany/yourls-popular-clicks-extended#7]
Just thought I'd mention that:

define ( "PCE_REL_VER",  '0.1' );
define ( "PCE_REL_DATE", '2014-07-16' );

– is out of date. Should be:

define ( "PCE_REL_VER",  '0.2' );
define ( "PCE_REL_DATE", '2015-12-30' );

=)
Oliver

**Comment by vaughany** [comment]
Sorted. Many thanks.
